//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emarketing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_client
    {
        public int cl_id { get; set; }
        public string cl_name { get; set; }
        public string email { get; set; }
        public Nullable<int> phone { get; set; }
    }
}
